### ISSUE TITLE
June 6th Call Changes

### ISSUE THREAD

**Issue by kdoran** [kdoran/socialpaktgithub#1]
1. Add to the twitter share field `@socialpakt` on default. Search for "twitter" in the product.htm template, you'll find "st_title" there, which is shared to twitter.
2. Add an 'estimated ship date' field to the product model. Have it display SOMEWHERE on the product page
   - on products that don't have inventory and are for sale and active (e.g. the four featured shirts, see [this page](https://github.com/kdoran/socialpaktgithub/wiki/Active-inventory-For-Sale-Etc)
   - on products that have inventory and are active, have them show "shipping is immediate"
   - on products that do not have inventory and are not for sale, don't show anything about shipping 
3. Add another filed that's a check box saying whether or not an artist is donating their money. From there, display a $9 instead of a $6 for every shirt's 'donation amount' on the product pages. Have it default to being 6

**Comment by Timmerop** [comment]
done
done
and done
just need to figure out how to push it all
